name: Python CI

on:
  push:
    branches: [ main ]  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment

        with:
          python-version: 3.x  # Specify the Python version you want to use (e.g., 3.6, 3.7, 3.8)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Run tests
        run: |
          python -m pytest tests/  # Run your tests using pytest or another testing framework

